# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog
description: > # this means to ignore newlines until "baseurl:"
  _(꒪ཀ꒪」∠)_
repository: https://armorfairy.github.com/blog
baseurl: /blog  # the subpath of your site, e.g. /blog
url: https://armorfairy.github.com/blog  # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Sass settings
sass:
  style: compressed

# Theme settings
theme_mode: dark  # choices are: 'dark', 'standard', 'markdown'

# Customizations
your_name: armor fairy
email: armorfairy420@gmail.com

navigation:
  - text: Home
    url: /
  - text: updates
    url: /up
  - text: archive
    url: /archive
  - text: info
    url: /info

projects:
  - name: chemdawg & moon puppy
    description: webcomic
    link: https://armorfairy.com/cdmp
    image: #


social:
  - service: github
    username: armorfairy
    link: https://github.com/armorfairy
    

# Plugins
gems:
  - jekyll-seo-tag
